services:
  db:
    image: postgres:16
    container_name: postgres_expense_db
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_expense_backend
    restart: always
    depends_on:
      - db
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["/bin/sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]

volumes:
  postgres_data: